kafka:
  application-id: ${KAFKA_STREAMS_APPLICATION_ID}
  brokers: ${KAFKA_BROKERS}
  ssl:
    truststorePath: ${KAFKA_TRUSTSTORE_PATH}
    keystorePath: ${KAFKA_KEYSTORE_PATH}
    credstorePsw: ${KAFKA_CREDSTORE_PASSWORD}
  schema-registry:
    url: ${KAFKA_SCHEMA_REGISTRY}
    user: ${KAFKA_SCHEMA_REGISTRY_USER}
    password: ${KAFKA_SCHEMA_REGISTRY_PASSWORD}
