name: Build and Deploy

on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths-ignore:
      - '.nais/topic-*.yml'
      - '.github/workflows/deploy-topics.yml'

env:
  IMAGE: ghcr.io/${{ github.repository }}:${{ github.sha }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@0.10.0
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 18
          distribution: 'temurin'

      - uses: gradle/gradle-build-action@v2.2.2
        env:
          GRADLE_BUILD_ACTION_CACHE_DEBUG_ENABLED: true
        with:
          arguments: test app:shadowJar --continue --no-daemon --no-build-cache

      - uses: dorny/test-reporter@v1.5.0
        if: success() || failure()
        with:
          name: ðŸ§¬ Test results
          path: "**/build/test-results/test/TEST-*.xml"
          reporter: java-junit
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish container
        run: |
          docker build --pull --tag ${{ env.IMAGE }} --tag ghcr.io/${{ github.repository }}:latest .
          docker push ghcr.io/${{ github.repository }} --all-tags

  deploy-dev:
    name: Deploy (dev)
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: nais/deploy/actions/deploy@v1
        env:
          PRINT_PAYLOAD: true
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: .nais/app.yml,.nais/alert.yml
          VARS: .nais/dev.yml
